### ISSUE TITLE
Disconnecting and joining at certain times

### ISSUE THREAD

**Issue by bstar16** [anOtherAnalyse/rawBot#2]
basically what the title says but can i make this join a server for a set amount of time then disconnect for a certain amount of time and repeat this process

**Comment by anOtherAnalyse** [comment]
Sure you could easily do this, just use ```this.disconnect()``` from the ```onTick()``` method of ```rawbot.bot.Bot``` when it is time to disconnect, and to join again just had a loop around the ```bot.run()``` call in your main class.
